export const CHANGE_SINGER_LIST = 'singers/CHANGE_SINGER_LIST';
export const CHANGE_PAGE_COUNT = 'singers/CHANGE_PAGE_COUNT';
export const CHANGE_ENTER_LOADING = 'singers/CHANGE_ENTER_LOADING';
export const CHANGE_IS_HAS_MORE = 'singers/CHANGE_IS_HAS_MORE';
export const CHANGE_IS_SHOW_PULL_UP_LOADING = 'singers/CHANGE_IS_SHOW_PULL_UP_LOADING';
export const CHANGE_IS_SHOW_PULL_DOWN_LOADING = 'singers/CHANGE_IS_SHOW_PULL_DOWN_LOADING';
